name: salon_symphony
description: A new Flutter project.
version: 2.8.18+15
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus:
  card_swiper: ^2.0.4
  shared_preferences:
  lottie:
  infinite_scroll_pagination:
  cached_network_image: ^3.2.1
  confetti: ^0.7.0
  custom_refresh_indicator: ^2.2.1
  flutter_linkify: ^5.0.2
  open_mail_app: ^0.4.5
  flutter_html:
  url_launcher: ^6.1.8
  sticky_grouped_list:
  readmore: ^2.2.0
  mask_text_input_formatter: ^2.5.0
  pdf_thumbnail: ^0.1.5+1
  audioplayers: ^4.1.0
  path_provider:
  video_thumbnail:
  alphabet_scroll_view:
  flutter_swipe_detector: ^2.0.0
  flutter_svg: ^1.1.6
  uni_links: ^0.5.1
  flutter_share:
  blur: ^3.1.0
  flutter_easyloading:
  expandable: ^5.0.1
  font_awesome_flutter: ^9.2.0
  flick_video_player: ^0.5.0
  video_player: ^2.3.8
  flutter_file_downloader: ^1.1.2
  amazon_cognito_identity_dart_2:
  flutter_rating_bar:
  flutter_time_picker_spinner: ^2.0.0
  azlistview: ^2.0.0
  keyboard_actions: 3.4.3
  dio: any
  internet_connection_checker:
  flutter_emoji: ^2.4.0
#  flutter_swiper_null_safety: ^1.0.2
  flip_card: ^0.6.0
  swipe_cards: ^1.0.0
  numberpicker:
  cupertino_icons: ^1.0.2
  flutter_tinder_swipe: ^0.0.4
  appinio_swiper: ^2.0.0
  scrollable_positioned_list:
#  google_sign_in: ^5.0.7
#  flutter_login_facebook: ^1.1.0
  flutter_switch: ^0.3.2
#  dotted_border: 2.0.0+1
  permission_handler: ^10.0.0
  flutter_datetime_picker: ^1.5.1
  file_picker: ^5.2.10
#  images_picker: ^1.2.11
  image_pickers: ^2.0.4+2
  animate_do: ^3.0.2
  rounded_loading_button:
  flutter_screenutil:
  fluttertoast: ^8.0.9
  shimmer: ^2.0.0
  step_progress_indicator: ^1.0.2
  buttons_tabbar: ^1.3.6
  mime: ^1.0.4
  sn_progress_dialog: ^1.1.3
  collection:
  uuid:
  intl_phone_number_input:
    git:
      url: https://github.com/AbdOoSaed/intl_phone_number_input
  pin_code_text_field: ^1.8.0
  intl: ^0.17.0
  webview_flutter: ^3.0.4

  # maps
  location: ^4.3.0
  google_maps_flutter: ^2.2.5
  flutter_cupertino_date_picker_fork: ^1.0.7

  #FIREBASE
  firebase_crashlytics: ^2.8.9
  firebase_database:
  firebase_auth:
  firebase_core:
  cloud_firestore:
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^13.0.4

  #Notificatidbusons
  flutter_local_notifications: ^9.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: any
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/
    - assets/lotties/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600

    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
